---
- name: Run Debian based tasks
  ansible.builtin.include_tasks: 
    file: "{{ tasks }}"
  loop:  
    - octoprint.yml
    - ustreamer.yml
  loop_control:
    loop_var: tasks

  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
