---
- name: Install common tools
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - python3
    - python3-pip
    - python3-virtualenv
    - acl
  become: true

- name: Create OctoPrint user
  ansible.builtin.user:
    name: "{{ octoprint_user }}"
    comment: "OctoPrint Service Account"
    create_home: false
    shell: /sbin/nologin
    groups: tty,dialout
    append: true
  become: true

- name: OctoPrint directories
  ansible.builtin.file:
    path: /opt/octoprint
    state: directory
    owner: "{{ octoprint_user }}"
    group: octoprint
  become: true

- name: Install OctoPrint
  ansible.builtin.pip:
    name: "OctoPrint=={{ octoprint_version }}"
    virtualenv: "/opt/octoprint/venv"
  become: true
  become_user: "{{ octoprint_user }}"
  notify: restart octoprint

- name: Create SystemD Service File for Octoprint
  ansible.builtin.template:
    src: octoprint.service.j2
    dest: /etc/systemd/system/octoprint.service
  become: true
  notify: restart octoprint
