---
# handlers file for octoprint_install
- name: restart octoprint
  ansible.builtin.systemd:
    name: octoprint
    state: restarted
    daemon_reload: true
    enabled: true
  become: true

- name: restart ustreamer
  ansible.builtin.systemd:
    name: ustreamer
    state: restarted
    daemon_reload: true
    enabled: true
  become: true